import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { ProyectsProvider } from "@/contexts/proyectsContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kanban Kno",
  description: "Generated by Kno Corporation",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased overflow-x-hidden">
        <ProyectsProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            value={{ light: "light", dark: "dark" }}
          >
            {children}
          </ThemeProvider>
        </ProyectsProvider>
      </body>
    </html>
  );
}
